import {escapeHtml,shell,statusBadge} from './common.js';

const value=(object,key,fallback='')=>object?.[key]??fallback;
const numberValue=value=>value===null||value===undefined?'':value;
const requiredValue=value=>value===true?'yes':value===false?'no':'pending';

export function render({flow}){
  const aircraft=flow.aircraft||{},rules=flow.rules||{},catalog=flow.aircraft_profiles||{items:[]};
  const selected=flow.selected_aircraft_profile_id||aircraft.aircraft_id||'';
  const profileOptions='<option value="">自定义/未选择</option>'+catalog.items.map(item=>'<option value="'+escapeHtml(item.aircraft_id)+'" '+(selected===item.aircraft_id?'selected':'')+'>'+escapeHtml(item.name)+' · '+escapeHtml(item.aircraft_id)+'</option>').join('');
  const routeOptions='<option value="">不指定</option>'+(flow.scenario_routes||[]).map(route=>'<option value="'+route.route_id+'" '+(aircraft.route_id===route.route_id?'selected':'')+'>'+route.route_id+' '+route.direction+'</option>').join('');
  const scopeOptions='<option value="project">项目默认需求</option>'+(flow.scenario_routes||[]).map(route=>'<option value="'+route.route_id+'">航路覆盖：'+route.route_id+'</option>').join('');
  const required=flow.required_cns||{},requirements=required.project_default||{},c=requirements.communication||{},n=requirements.navigation||{},s=requirements.surveillance||{};
  const requirementRow=(prefix,title,data,fields)=>'<fieldset class="cns-requirement"><legend>'+title+' '+statusBadge(data.status||'pending_confirmation')+'</legend><label>是否需要<select id="'+prefix+'Required"><option value="pending" '+(requiredValue(data.required)==='pending'?'selected':'')+'>待确认</option><option value="yes" '+(data.required===true?'selected':'')+'>需要</option><option value="no" '+(data.required===false?'selected':'')+'>不需要</option></select></label>'+fields.map(([key,label,type])=>'<label>'+label+'<input '+(type||'type="number" step="any" min="0"')+' id="'+prefix+key+'" value="'+escapeHtml(numberValue(data[key]))+'"></label>').join('')+'</fieldset>';
  const profileSummary=catalog.items.map(item=>item.aircraft_id===selected?'<div class="flow-summary">已有能力仅作为 capability：C '+escapeHtml((item.communication?.capabilities||[]).join(', ')||'待确认')+'；N '+escapeHtml((item.navigation?.capabilities||[]).join(', ')||'待确认')+'；S '+escapeHtml((item.surveillance?.capabilities||[]).join(', ')||'待确认')+'</div>':'').join('');
  const body='<div class="demo-note">AircraftCNSProfileCatalog：'+escapeHtml(flow.aircraft_source)+' · '+catalog.count+' 条；不会自动成为 RequiredCNS</div><label>飞行器能力档案<select id="aircraftProfile">'+profileOptions+'</select></label>'+profileSummary+
    '<div class="form-grid"><label>厂家<input id="manufacturer" value="'+escapeHtml(value(aircraft,'manufacturer','工程测试厂家'))+'"></label><label>型号<input id="model" value="'+escapeHtml(value(aircraft,'model','Demo-A1'))+'"></label><label>巡航速度 m/s<input type="number" id="cruise" value="'+value(aircraft,'cruise_speed_mps',25)+'"></label><label>最大速度 m/s<input type="number" id="maximum" value="'+value(aircraft,'max_speed_mps',40)+'"></label><label>MTBF h<input type="number" id="mtbf" value="'+value(aircraft,'mtbf_h',10000)+'"></label><label>绑定航路<select id="aircraftRoute">'+routeOptions+'</select></label><label>A→B 高度 m<input type="number" id="heightAB" value="'+value(rules,'height_ab_m',120)+'"></label><label>B→A 高度 m<input type="number" id="heightBA" value="'+value(rules,'height_ba_m',150)+'"></label><label>高度模式<select id="heightMode"><option value="different">双向不同高度</option><option value="same">同高度层</option></select></label><label>水平间隔 m<input type="number" id="separation" value="'+value(rules,'horizontal_separation_m',100)+'"></label><label>感知→平台 ms<input type="number" id="delaySensor" value="'+value(rules,'delay_sensor_to_platform_ms',500)+'"></label><label>平台→航空器 ms<input type="number" id="delayCommand" value="'+value(rules,'delay_platform_to_aircraft_ms',500)+'"></label></div><label>方向规则<select id="directionRule"><option>按航向分层</option><option>同一航路仅一架</option><option>同一方向仅一架</option></select></label><button class="primary full" id="saveRules">保存并校验规则</button>'+
    (flow.aircraft?'<div class="flow-summary">λ='+(flow.aircraft.lambda_per_hour*1000000).toFixed(3)+'×10⁻⁶/h · 总时延 '+rules.total_delay_ms+' ms · 反应距离 '+rules.reaction_distance_m+' m<br>'+statusBadge(rules.status)+' '+escapeHtml(rules.message)+'</div>':'')+
    '<h3>RequiredCNS</h3><label>需求作用域<select id="requiredScope">'+scopeOptions+'</select></label><div class="cns-requirements">'+
    requirementRow('c','Communication',c,[['Coverage','覆盖要求 %'],['MaxGap','最大缺口 m'],['Latency','最大时延 ms'],['Redundancy','冗余数量']])+
    requirementRow('n','Navigation',n,[['Coverage','覆盖要求 %'],['Accuracy','精度 m'],['Integrity','完整性说明','type="text"'],['Redundancy','冗余数量']])+
    requirementRow('s','Surveillance',s,[['Coverage','覆盖要求 %'],['Update','更新间隔 s'],['Redundancy','冗余数量']])+
    '</div><button class="secondary full" id="saveRequiredCns">保存 RequiredCNS</button><div class="parameter-note">未填写的需求保持 pending_confirmation；不自动使用飞行器已有能力，也不提供法规默认阈值。</div><button class="secondary full" id="nextStep" '+(!flow.steps['4']?'disabled':'')+'>下一步：设备与布站</button>';
  return shell('04','运行规则','飞行器已有能力、任务需求和运行规则分别保存。',body);
}

export function bind(c){
  const flow=c.flow();if(flow.rules)c.$('heightMode').value=flow.rules.height_mode;
  c.$('aircraftProfile').onchange=event=>{const profile=flow.aircraft_profiles.items.find(item=>item.aircraft_id===event.target.value);if(!profile)return;c.$('manufacturer').value=profile.manufacturer||'';c.$('model').value=profile.model||'';for(const [id,key] of [['cruise','cruise_speed_mps'],['maximum','max_speed_mps'],['mtbf','mtbf_h']])if(profile[key]!=null)c.$(id).value=profile[key];};
  c.actionButton('saveRules',async()=>{await c.mutate('rules',{aircraft_id:c.$('aircraftProfile').value,manufacturer:c.$('manufacturer').value,model:c.$('model').value,cruise_speed:c.$('cruise').value,max_speed:c.$('maximum').value,mtbf:c.$('mtbf').value,route_id:c.$('aircraftRoute').value,height_ab:c.$('heightAB').value,height_ba:c.$('heightBA').value,height_mode:c.$('heightMode').value,horizontal_separation:c.$('separation').value,direction_rule:c.$('directionRule').value,delay_sensor:c.$('delaySensor').value,delay_command:c.$('delayCommand').value});if(c.flow().rules?.status==='passed')await c.mutate('operational');});
  const optional=id=>c.$(id).value===''?null:Number(c.$(id).value),required=id=>({yes:true,no:false,pending:null})[c.$(id).value];
  c.actionButton('saveRequiredCns',()=>{const selectedScope=c.$('requiredScope').value,payload={scope:selectedScope==='project'?'project':'route',route_id:selectedScope==='project'?null:selectedScope,requirements:{communication:{required:required('cRequired'),coverage_requirement:optional('cCoverage'),max_gap_m:optional('cMaxGap'),latency_ms:optional('cLatency'),redundancy:optional('cRedundancy')},navigation:{required:required('nRequired'),coverage_requirement:optional('nCoverage'),accuracy_m:optional('nAccuracy'),integrity:c.$('nIntegrity').value.trim()||null,redundancy:optional('nRedundancy')},surveillance:{required:required('sRequired'),coverage_requirement:optional('sCoverage'),update_interval_s:optional('sUpdate'),redundancy:optional('sRedundancy')}}};return c.mutate('required-cns',payload);});
  if(c.$('nextStep'))c.$('nextStep').onclick=()=>c.setStep(5);
}
