"""专题制图模板（Presentation / Cartographic Export）。

只包含**版式与样式目录**：模板声明、图层样式键、图例分组。这里没有任何业务算法，
也不打开任何数据集；真正的 QGIS 对象创建在 :mod:`cns_planner.gis.qgis_figure_renderer`。
"""

from .template_catalog import (  # noqa: F401
    AVAILABLE, CNS_COMBINED_V1, CNS_COMBINED_V1_TEMPLATE, CNS_COVERAGE_POLICY,
    CNS_EXTENT_POLICY_ID, CNS_LAYOUT_PROFILE, CNS_LAYOUT_PROFILE_V1, CNS_LEGEND_ORDER,
    CNS_SERVICE_COLORS,
    CNS_SHARED_PARAMETERS, COMMERCIAL_TEMPLATES, COMMUNICATION_LAYOUT_V1,
    COMMUNICATION_LAYOUT_V1_TEMPLATE, LAYER_DISPLAY_NAMES, LAYER_SOURCE_ROLES,
    MAX_PARAMETER_PIXELS, MapFigureParameterInvalid, NAVIGATION_LAYOUT_V1,
    NAVIGATION_LAYOUT_V1_TEMPLATE, PARAMETER_CONSTRAINTS, PLANNED,
    ROUTE_DETAIL_V1, ROUTE_OVERVIEW_LEGEND_ORDER, ROUTE_OVERVIEW_PARAMETERS,
    ROUTE_OVERVIEW_V1, ROUTE_OVERVIEW_V1_TEMPLATE, SURVEILLANCE_LAYOUT_V1,
    SURVEILLANCE_LAYOUT_V1_TEMPLATE, SURVEILLANCE_SERVICE_PARAMETER,
    SURVEILLANCE_SERVICE_RADAR, SURVEILLANCE_SERVICE_RID, SURVEILLANCE_SERVICE_VALUES,
    TEMPLATE_SCHEMA_VERSION, catalog, is_available, parameters, required_parameters,
    template,
)

#: 本轮的 CNS 专题模板集合（制图分派与测试共用）。
CNS_TEMPLATE_IDS = (
    COMMUNICATION_LAYOUT_V1, SURVEILLANCE_LAYOUT_V1, NAVIGATION_LAYOUT_V1,
    CNS_COMBINED_V1,
)

__all__ = [
    "AVAILABLE", "CNS_COMBINED_V1", "CNS_COMBINED_V1_TEMPLATE", "CNS_COVERAGE_POLICY",
    "CNS_EXTENT_POLICY_ID", "CNS_LAYOUT_PROFILE", "CNS_LAYOUT_PROFILE_V1", "CNS_LEGEND_ORDER",
    "CNS_SERVICE_COLORS",
    "CNS_SHARED_PARAMETERS", "CNS_TEMPLATE_IDS", "COMMERCIAL_TEMPLATES",
    "COMMUNICATION_LAYOUT_V1", "COMMUNICATION_LAYOUT_V1_TEMPLATE", "LAYER_DISPLAY_NAMES",
    "LAYER_SOURCE_ROLES", "MAX_PARAMETER_PIXELS", "MapFigureParameterInvalid",
    "NAVIGATION_LAYOUT_V1", "NAVIGATION_LAYOUT_V1_TEMPLATE", "PARAMETER_CONSTRAINTS",
    "PLANNED", "ROUTE_DETAIL_V1", "ROUTE_OVERVIEW_LEGEND_ORDER",
    "ROUTE_OVERVIEW_PARAMETERS", "ROUTE_OVERVIEW_V1", "ROUTE_OVERVIEW_V1_TEMPLATE",
    "SURVEILLANCE_LAYOUT_V1", "SURVEILLANCE_LAYOUT_V1_TEMPLATE",
    "SURVEILLANCE_SERVICE_PARAMETER", "SURVEILLANCE_SERVICE_RADAR",
    "SURVEILLANCE_SERVICE_RID", "SURVEILLANCE_SERVICE_VALUES", "TEMPLATE_SCHEMA_VERSION",
    "catalog", "is_available", "parameters", "required_parameters", "template",
]
